version: '3.1'
services:
  web:
    volumes:
      - ./app:/app
    environment:
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=7000'
    command: flask run --host=0.0.0.0 --port=7000
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
