# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
        - image: docker:17-git
    steps:
      - setup_remote_docker:
            docker_layer_caching: true
      - run: apk --no-cache add py-pip && pip install 'docker-compose==1.18.0'
      - checkout
      - run: cp .env.dist .env
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD quay.io
      - run: |
          export TAG=${CIRCLE_BRANCH}
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

workflows:
  version: 2
  build_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
