"""empty message

Revision ID: 24a224e1ec75
Revises: 075d085d06a6
Create Date: 2018-04-19 18:31:28.557444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24a224e1ec75'
down_revision = '075d085d06a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'file_id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.add_column('events', sa.Column('private', sa.Boolean(), nullable=False))
    op.add_column('files', sa.Column('filename', sa.String(length=64), nullable=False))
    op.add_column('files', sa.Column('type', sa.Enum('IMAGE', 'VIDEO', name='filetypeenum'), nullable=False))
    op.create_unique_constraint(None, 'files', ['filename'])
    op.alter_column('reactions', 'type',
               existing_type=mysql.ENUM('LIKE', 'DISLIKE', 'LOVE', 'HAPPY', 'SAD', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.add_column('resources', sa.Column('resource_type', sa.String(length=64), nullable=False))
    op.drop_column('resources', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False))
    op.drop_column('resources', 'resource_type')
    op.alter_column('reactions', 'type',
               existing_type=mysql.ENUM('LIKE', 'DISLIKE', 'LOVE', 'HAPPY', 'SAD', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_column('files', 'type')
    op.drop_column('files', 'filename')
    op.drop_column('events', 'private')
    op.drop_table('tags')
    op.drop_table('membership')
    op.drop_table('groups')
    op.drop_table('file_tag')
    # ### end Alembic commands ###
