"""empty message

Revision ID: 6064c503a0dd
Revises: dd3f084d8c66
Create Date: 2018-03-28 11:06:37.250433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6064c503a0dd'
down_revision = 'dd3f084d8c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Annees', ['annees'])
    op.drop_constraint('Dossier_ibfk_1', 'Dossier', type_='foreignkey')
    op.drop_constraint('Dossier_ibfk_2', 'Dossier', type_='foreignkey')
    op.create_foreign_key(None, 'Dossier', 'Annees', ['annees'], ['annees'])
    op.create_foreign_key(None, 'Dossier', 'Events', ['events'], ['events'])
    op.create_unique_constraint(None, 'Events', ['events'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Events', type_='unique')
    op.drop_constraint(None, 'Dossier', type_='foreignkey')
    op.drop_constraint(None, 'Dossier', type_='foreignkey')
    op.create_foreign_key('Dossier_ibfk_2', 'Dossier', 'Events', ['events'], ['id'])
    op.create_foreign_key('Dossier_ibfk_1', 'Dossier', 'Annees', ['annees'], ['id'])
    op.drop_constraint(None, 'Annees', type_='unique')
    # ### end Alembic commands ###
