"""empty message

Revision ID: dd3f084d8c66
Revises:
Create Date: 2018-03-27 21:53:08.405763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3f084d8c66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Annees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annees', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('events', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Dossier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annees', sa.Integer(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('couv', sa.Boolean(), nullable=False),
    sa.Column('cat', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['annees'], ['Annees.id'], ),
    sa.ForeignKeyConstraint(['events'], ['Events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Dossier')
    op.drop_table('Events')
    op.drop_table('Annees')
    op.drop_table('Admin')
    # ### end Alembic commands ###
